/*
 * HULTRASONIC_Private.h
 *
 *  Created on: Mar 21, 2022
 *      Author: Dell
 */

#ifndef HAL_HULTRASONIC_HULTRASONIC_PRIVATE_H_
#define HAL_HULTRASONIC_HULTRASONIC_PRIVATE_H_



#endif /* HAL_HULTRASONIC_HULTRASONIC_PRIVATE_H_ */
